### ISSUE TITLE
todo

### ISSUE THREAD

**Issue by ascoders** [fex-team/gaea#2]
## 编译
- [x] 优化css的namespace，现在需要在div指定namespace替换成当前路径
- [x]  css-path-loader 通过 js 和 css 同时替换_namespace ，提供设置组件最外层 css 样式的功能
- [x]  html-path-loader 兼容外层存在 className 的情况
## 编辑器
- [x] 生成组件时传递的opts由全量改为增量
- [x] 有时修改并没有立即生效
- [x] loading页面完成
- [x] 绝对定位组件预览定位错误
- [x] 在toolbar时同步阻塞获取配置信息、组件树信息
- [x] hover时显示轮廓
- [x] 宽度改为百分比
- [x] 宽度支持像素、百分比、grow
- [x] 宽度组件视觉优化
- [x] 精简edit文件大小，拆分模块
- [x] selector跟上修改的视觉效果
- [x] 复制粘贴功能
- [x] 复制粘贴快捷键
- [x] 保存快捷键
- [x] 新增模板
- [x] 新增删除快捷键 (delete)
- [x] 修复绝对定位组件拖拽时动画延迟
- [x] 选中外边框换成绝对定位div，并增加拖拽功能
- [ ] 修改产生的历史纪录改为由left/edit组件触发
- [x] number组件不识别浮点类型
- [x] 右侧增加可选模板
- [ ] 预览和hover/selector时有Mutating `style` is deprecated报错
- [ ] selector增加宽高拖拽按钮
- [x] 删除时hover/selector位置没有更新
- [ ] 整个页面滚动条消失时，hover/selector位置没有更新
- [ ] 用editorStore的container取代historyStore
- [ ] 颜色可选继承
- [ ] 选中code组件后，编辑框变宽
- [ ] 编辑框title宽度固定
- [x] 组件悬浮之后子级元素缩小
## 页面
- [ ] 多页面路由
- [x] 选择组件后，复用选择框，类似office平滑移动
- [ ] 触发缩小bug优化
- [ ] 页面中组件拖拽缩小，会出现无法恢复的bug
- [ ] 缩放拖拽结束后selector位置优化
- [ ] 保存功能
- [x] 偶尔出现选择框没有消除，导致存在2个以上的选择框
- [x] 多分辨率预览
- [x] 拖拽后动画缩小，hover 1秒后所有同级元素缩小
- [x] 拖拽元素不能拖动到自己、自己的父级、自己的任意子元素
- [x] absolute组件移动过程中保持边框，并隐藏原来组件
- [x] 拖拽缩小时，如果hover组件是当前拖拽的组件，不应该触发缩放
- [x] 删除组件时selector同时被隐藏
- [x] selector选中外侧，选不中内测，且选择一个就渲染全部的bug复现
- [ ] command+delete删除改为delete删除，焦点在输入框时不会删除
## 后端
- [ ] 支持配置存储
## 树状结构
- [ ] 树中拖拽
- [ ] 编辑区与树的双向拖拽
## 历史纪录
- [x] 恢复组件时，宽度还是默认值
- [x] uniqueKey冲突问题
- [ ] 颜色等组件因为多次对其赋值，无法根据上一个状态找到最初的值
- [ ] 还原时因为没有加上位置信息，导致还原被删除组件时位置错误
- [ ] 回退bug
## 预览
- [x] 预览时编辑状态消失，退出预览时，重新自动选择之前选择的组件
- [x] 有时候预览是空的
- [x] 基础预览功能
- [x] 预览时动画效果
- [x] 分辨率切换后，更新selector的位置
- [x] 预览后切换分辨率，再切换回去，selector丢失问题修复
## 树
- [x] 树支持页面模板
- [x] 树支持复制粘贴
- [ ] 跟随滚动
